# Generated by Django 3.1.7 on 2021-03-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_userresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerobjective',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userresume'),
        ),
        migrations.AddField(
            model_name='educationbackground',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userresume'),
        ),
        migrations.AddField(
            model_name='employment',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userresume'),
        ),
        migrations.AddField(
            model_name='interest',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userresume'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userresume'),
        ),
        migrations.AddField(
            model_name='references',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userresume'),
        ),
        migrations.AddField(
            model_name='skills',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userresume'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
